print("Welcome to the band name generator")
city = input("Which city did you grow up in?")
print(city)
pet = input("What is the name of a pet?")
print(pet)
print("Your band name could be "+city+" "+ pet)